# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d3c70d601c410a1d92e43e5de065aff5eb595200fb184ae68b6afabdef39442dd2f357a4122cde1b3b227f6517cdc13465c5bcf9a9d79580bb90392055d86a1

test:
  secret_key_base: df40ca91e1aca6588c994793b7fdec136c2427953d1f98dbbb5955ac0aa95033ecafa45ea0c9742191dc6ae61286bb1df7360ee85bd5535a0eee12027340df39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
